from tkinter import *
top=Tk()
top.geometry("1400x800")
top.title("DIVYAASHRE")
top.config(bg="BLACK")
def login():
    rocky=Frame(top,bg="SKYBLUE4",height=700,width=400)
    rocky.pack(fill=X)
    button=Button(top,text="BACK",font=("TIMES NEW ROMAN",30,'italic'),bg="WHITE",fg="BLACK",activebackground="WHITE",activeforeground="BLACK",command=login)
    button.place(x=10,y=10,width=200,height=70)
    label1=Label(rocky,text="Login  Page",font=("TIMES NEW ROMAN",40,'italic'),bg="SKYBLUE4",fg="WHITE")
    label1.place(x=500,y=100)
    label1=Label(rocky,text="Username ",font=("TIMES NEW ROMAN",30,'italic'),bg="SKYBLUE4",fg="WHITE")
    label1.place(x=700,y=200)
    box=Entry(top,text="",font=("TIMES NEW ROMAN",20,'italic'),bg="WHITE",fg="BLACK")
    box.place(x=900,y=200,width=400,height=50)
    label1=Label(rocky,text="Password ",font=("TIMES NEW ROMAN",30,'italic'),bg="SKYBLUE4",fg="WHITE")
    label1.place(x=700,y=275)
    box=Entry(top,text="",font=("TIMES NEW ROMAN",20,'italic'),bg="WHITE",fg="BLACK")
    box.place(x=900,y=275,width=400,height=50)
    button=Button(top,text="LOGIN",font=("TIMES NEW ROMAN",30,'italic'),bg="WHITE",fg="BLACK",activebackground="WHITE",activeforeground="BLACK",command=login)
    button.place(x=800,y=400,width=200,height=70)
    label1=Label(rocky,text="Don't have an account? ",font=("TIMES NEW ROMAN",24,'italic'),bg="SKYBLUE4",fg="WHITE")
    label1.place(x=700,y=600)
    button=Button(top,text="SIGN IN",font=("TIMES NEW ROMAN",30,'italic'),bg="RED",fg="BLACK",activebackground="RED",activeforeground="BLACK",command=login)
    button.place(x=1015,y=595,width=200,height=70)
DETAILS=Label(top,text="WELCOME OUR PAGE",font=("TIMES NEW ROMAN",30,'italic'),bg="BLACK",fg="WHITE")
DETAILS.place(x=525,y=100)

button=Button(top,text="GET STARTED",font=("TIMES NEW ROMAN",20,'italic'),bg="WHITE",fg="BLACK",activebackground="WHITE",activeforeground="BLACK",command=login)
button.place(x=400,y=500,width=600,height=70)
top.mainloop()
